"""Interactive chat test for MasterAgent with real OpenAI API.

This allows you to have a real-time conversation with the master agent:
1. Start with initial idea/title
2. Chat and refine requirements
3. Generate full proposal when ready
4. Make edits and see which agents rerun

Run:
  python -m agents.master_agent.chat_test
"""

import json
import os
from datetime import datetime
from typing import Any, Dict, List

from agents.config import env
from agents.llm import get_llm
from agents.master_agent.agent import MasterAgent


class MockSession:
    """Mock session object that tracks state for testing."""

    def __init__(self):
        self.is_proposal_generated = False
        self.current_stage = "initial"
        self.proposal_title = None
        self.initial_idea = ""
        self.conversation_history: List[Dict[str, str]] = []
        self.document = None
        self._agent_responses: Dict[str, str] = {}
        self._final_proposal_html: str = ""

    def get_conversation_history(self) -> List[Dict[str, str]]:
        return self.conversation_history

    def add_message(self, role: str, message: str):
        self.conversation_history.append({"role": role, "message": message})

    def get_all_current_responses(self):
        """Return mock agent responses for HTML compilation."""
        return []  # Simplified for chat test

    def get_compiled_proposal_html(self) -> str:
        """Return compiled proposal HTML from state."""
        # Return HTML from final_proposal if available, otherwise generate basic structure
        if self._final_proposal_html:
            return self._final_proposal_html
        
        # Basic HTML structure if no final proposal yet
        title = self.proposal_title or "Project Proposal"
        return f"""
        <h1>{title}</h1>
        <section id="initial_idea">
            <h2>1. Initial Business Idea</h2>
            <p>{self.initial_idea or 'Project idea'}</p>
        </section>
        <section id="scope">
            <h2>2. Refined Project Scope</h2>
            <p>Scope details will be generated by agents.</p>
        </section>
        """

    def save(self):
        """Mock save method."""
        pass


class MockAgentType:
    """Mock agent type for testing."""

    def __init__(self, name: str, display_name: str):
        self.name = name
        self.display_name = display_name


class MockAgentResponse:
    """Mock agent response for testing."""

    def __init__(self, agent_type_name: str, content: str):
        self.agent_type = MockAgentType(agent_type_name, agent_type_name)
        self.response_content = content


def print_separator():
    """Print a visual separator."""
    print("\n" + "=" * 80 + "\n")


def print_agent_info():
    """Print available agent information."""
    print("\n📋 Available Agents:")
    agents = [
        ("scope_refinement", "Refines project scope and features"),
        ("business_analyst", "Business analysis and market research"),
        ("technical_architect", "Technical specifications and architecture"),
        ("project_manager", "Project timeline and milestones"),
        ("resource_allocation", "Team composition and budget"),
    ]
    for name, desc in agents:
        print(f"  • {name}: {desc}")


def save_html_to_file(html_content: str, title: str = "proposal") -> str:
    """Save HTML content to a file.
    
    Args:
        html_content: HTML content to save
        title: Base name for the file (will add timestamp)
        
    Returns:
        Path to the saved file
    """
    # Create output directory if it doesn't exist
    output_dir = "proposals"
    os.makedirs(output_dir, exist_ok=True)
    
    # Generate filename with timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_title = "".join(c for c in title if c.isalnum() or c in (' ', '-', '_')).strip()[:50]
    safe_title = safe_title.replace(' ', '_').lower()
    filename = f"{safe_title}_{timestamp}.html"
    filepath = os.path.join(output_dir, filename)
    
    # Write HTML to file
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(html_content)
    
    return filepath


def main():
    """Run interactive chat with MasterAgent."""
    print_separator()
    print("🤖 Master Agent Interactive Chat Test")
    print_separator()
    print("Commands:")
    print("  - Type normally to chat")
    print("  - Say 'generate proposal' or 'generate' to create full proposal")
    print("  - Ask for edits (e.g., 'add social login', 'change timeline to 4 months')")
    print("  - Type 'quit' or 'exit' to end")
    print_separator()

    # Check API key
    if not env.openai_api_key:
        print("❌ ERROR: OPENAI_API_KEY not found in environment.")
        print("Please set it in your .env file or export it.")
        return

    # Initialize
    session = MockSession()
    llm = get_llm(temperature=0.7)
    master_agent = MasterAgent(llm=llm, session=session)

    state: Dict[str, Any] = {
        "llm": llm,
        "initial_idea": "",
        "conversation_context": "",
    }

    print("💬 Starting conversation...\n")

    # Initial greeting
    print("Master Agent: 👋 Hi! I'm here to help you create a proposal.")
    print("Master Agent: Please tell me about your project idea.\n")

    while True:
        try:
            # Get user input
            user_input = input("You: ").strip()

            if not user_input:
                continue

            # Check for exit commands
            if user_input.lower() in ["quit", "exit", "q"]:
                print("\n👋 Goodbye!")
                break

            # Add to conversation history
            session.add_message("user", user_input)

            # Update state
            if not state.get("initial_idea"):
                state["initial_idea"] = user_input
                session.initial_idea = user_input

            # Route the request
            print("\n🎯 Master Agent is thinking...")
            routing_decision = master_agent.route_request(
                user_message=user_input,
                session=session,
                state=state,
            )

            action = routing_decision.get("action")
            agents_to_rerun = routing_decision.get("agents_to_rerun", [])

            print(f"\n📊 Routing Decision: {action}")
            if agents_to_rerun:
                print(f"🔄 Agents to rerun: {', '.join(agents_to_rerun)}")

            # Handle different actions
            if action == "conversation":
                # Handle conversation
                print("\n💬 Master Agent (conversation mode):")
                conversation_result = master_agent.handle_conversation(
                    user_message=user_input,
                    session=session,
                    state=state,
                )
                response_message = conversation_result.get(
                    "message", "I understand. Tell me more about your project."
                )
                print(f"  {response_message}")

                # Add assistant response to history
                session.add_message("assistant", response_message)

                # Check if ready for proposal
                if conversation_result.get("ready_for_proposal"):
                    print("\n✨ Master Agent: I have enough information!")
                    print("   Say 'generate proposal' when you're ready.\n")

            elif action == "generate_proposal":
                print("\n🚀 Master Agent: Generating full proposal...")
                print("   This will run all agents:")
                print("   1. Title")
                print("   2. Scope Refinement")
                print("   3. Business Analyst")
                print("   4. Technical Architect")
                print("   5. Project Manager")
                print("   6. Resource Allocation")
                print("   7. Final Compilation")

                # Execute pipeline
                try:
                    updated_state = master_agent.execute_pipeline(
                        routing_decision=routing_decision,
                        session=session,
                        state=state,
                    )
                    state.update(updated_state)
                    session.is_proposal_generated = True
                    session.current_stage = "completed"
                    
                    # Store final proposal HTML if available
                    final_html = ""
                    if "final_proposal" in updated_state:
                        final_proposal = updated_state.get("final_proposal", {})
                        if isinstance(final_proposal, dict):
                            final_html = final_proposal.get("html_content", "")
                            session._final_proposal_html = final_html
                            if session.proposal_title is None and "proposal_title" in updated_state:
                                session.proposal_title = updated_state["proposal_title"]
                    
                    # Also check if HTML was updated in session
                    if not final_html and hasattr(session, "document") and session.document:
                        if hasattr(session.document, "document"):
                            final_html = session.document.document
                    elif not final_html:
                        # Fallback to compiled HTML
                        final_html = session.get_compiled_proposal_html()
                    
                    # Save HTML to file
                    if final_html:
                        title = session.proposal_title or state.get("proposal_title", "proposal")
                        filepath = save_html_to_file(final_html, title)
                        print(f"\n💾 Proposal saved to: {filepath}")

                    print("\n✅ Proposal generated successfully!")
                    # Show sections generated per agent if available
                    sections_generated = updated_state.get("sections_generated", {}) if isinstance(updated_state, dict) else {}
                    if sections_generated:
                        print("   📑 Sections generated by agents:")
                        for agent_name, sections in sections_generated.items():
                            print(f"   - {agent_name}: {', '.join(sections)}")
                    print(
                        "   You can now ask for edits (e.g., 'change budget to $60k')\n"
                    )

                except Exception as e:
                    print(f"\n⚠️ Pipeline execution note: {e}")
                    import traceback
                    traceback.print_exc()

            elif action == "edit":
                print(f"\n✏️ Master Agent: Making edits...")
                print(f"   Will rerun: {', '.join(agents_to_rerun)}")

                # Show dependency expansion
                expanded = master_agent.get_sub_agents_to_rerun(
                    routing_decision, session
                )
                if len(expanded) > len(agents_to_rerun):
                    print(f"   Including dependencies: {', '.join(expanded)}")

                # Execute pipeline for edits
                try:
                    updated_state = master_agent.execute_pipeline(
                        routing_decision=routing_decision,
                        session=session,
                        state=state,
                    )
                    state.update(updated_state)
                    
                    # Get updated HTML and save to file
                    updated_html = ""
                    if hasattr(session, "document") and session.document:
                        if hasattr(session.document, "document"):
                            updated_html = session.document.document
                    if not updated_html:
                        updated_html = session.get_compiled_proposal_html()
                    
                    if updated_html:
                        title = session.proposal_title or state.get("proposal_title", "proposal")
                        filepath = save_html_to_file(updated_html, f"{title}_updated")
                        print(f"\n💾 Updated proposal saved to: {filepath}")
                    
                    # Show sections generated on edit as well
                    sections_generated = updated_state.get("sections_generated", {}) if isinstance(updated_state, dict) else {}
                    if sections_generated:
                        print("\n   📑 Sections updated by agents:")
                        for agent_name, sections in sections_generated.items():
                            print(f"   - {agent_name}: {', '.join(sections)}")
                    print("\n✅ Edits applied!")
                except Exception as e:
                    print(f"\n⚠️ Edit execution note: {e}")
                    import traceback
                    traceback.print_exc()

            print()

        except KeyboardInterrupt:
            print("\n\n👋 Chat interrupted. Goodbye!")
            break
        except Exception as e:
            print(f"\n❌ Error: {e}")
            import traceback

            traceback.print_exc()
            print("\nContinuing...\n")


if __name__ == "__main__":
    main()

